export const PokeTypes = {
  normal: {
    label: 'NORMAL',
    color: '#A8A878',
  },
  fighting: {
    label: 'FIGHT',
    color: '#C03028',
  },
  flying: {
    label: 'FLYING',
    color: '#A890F0',
  },
  poison: {
    label: 'POISON',
    color: '#A040A0',
  },
  ground: {
    label: 'GROUND',
    color: '#E0C068',
  },
  rock: {
    label: 'ROCK',
    color: '#B8A038',
  },
  bug: {
    label: 'BUG',
    color: '#A8B820',
  },
  ghost: {
    label: 'GHOST',
    color: '#705898',
  },
  steel: {
    label: 'STEEL',
    color: '#B8B8D0',
  },
  fire: {
    label: 'FIRE',
    color: '#F08030',
  },
  water: {
    label: 'WATER',
    color: '#6890F0',
  },
  grass: {
    label: 'GRASS',
    color: '#78C850',
  },
  electric: {
    label: 'ELECTR',
    color: '#F8D030',
  },
  psychic: {
    label: 'PSYCHC',
    color: '#F85888',
  },
  ice: {
    label: 'ICE',
    color: '#98D8D8',
  },
  dragon: {
    label: 'DRAGON',
    color: '#7038F8',
  },
  dark: {
    label: 'DARK',
    color: '#705848',
  },
} as const

export type PokeType = keyof typeof PokeTypes

export const PokeTypeEffectives: Record<PokeType, Partial<Record<PokeType, number>>> = {
  normal: {
    rock: 0.5,
    steel: 0.5,
    ghost: 0,
  },
  fire: {
    fire: 0.5,
    water: 0.5,
    grass: 2,
    ice: 2,
    bug: 2,
    rock: 0.5,
    dragon: 0.5,
    steel: 2,
  },
  water: {
    fire: 2,
    water: 0.5,
    grass: 0.5,
    ground: 2,
    rock: 2,
    dragon: 0.5,
  },
  electric: {
    water: 2,
    electric: 0.5,
    grass: 0.5,
    ground: 0,
    flying: 2,
    dragon: 0.5,
  },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5,
  },
  ice: {
    water: 0.5,
    grass: 2,
    ice: 0.5,
    ground: 2,
    flying: 2,
    dragon: 2,
    steel: 0.5,
    fire: 0.5,
  },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    dark: 2,
    steel: 2,
    ghost: 0,
  },
  poison: {
    grass: 2,
    poison: 0.5,
    ground: 0.5,
    rock: 0.5,
    ghost: 0.5,
    steel: 0,
  },
  ground: {
    fire: 2,
    electric: 2,
    grass: 0.5,
    poison: 2,
    flying: 0,
    bug: 0.5,
    rock: 2,
    steel: 2,
  },
  flying: {
    electric: 0.5,
    grass: 2,
    fighting: 2,
    bug: 2,
    rock: 0.5,
    steel: 0.5,
  },
  psychic: {
    fighting: 2,
    poison: 2,
    psychic: 0.5,
    dark: 0,
    steel: 0.5,
  },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
  },
  rock: {
    fire: 2,
    ice: 2,
    fighting: 0.5,
    ground: 0.5,
    flying: 2,
    bug: 2,
    steel: 0.5,
  },
  ghost: {
    normal: 0,
    psychic: 2,
    dark: 0.5,
    steel: 0.5,
    ghost: 2,
  },
  dragon: {
    dragon: 2,
    steel: 0.5,
  },
  dark: {
    fighting: 0.5,
    psychic: 2,
    ghost: 2,
    dark: 0.5,
    steel: 0.5,
  },
  steel: {
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    ice: 2,
    rock: 2,
    steel: 0.5,
  },
}
